import os
import sys

# Add backend directory to path
sys.path.append(os.path.dirname(os.path.abspath(__file__)))

from app import create_app
from app.services.auth_service import token_to_uid

app = create_app()

PATIENT_TOKEN = "eyJhbGciOiJSUzI1NiIsImtpZCI6ImE1YTAwNWU5N2NiMWU0MjczMDBlNTJjZGQ1MGYwYjM2Y2Q4MDYyOWIiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vdGltZXRhYmxlLWdlbmVyYXRvci04OWYyOCIsImF1ZCI6InRpbWV0YWJsZS1nZW5lcmF0b3ItODlmMjgiLCJhdXRoX3RpbWUiOjE3NjAyNjczMzMsInVzZXJfaWQiOiJnN2hJeUxPamh4VW1sM09JZ2RGaFBkaFNhcGMyIiwic3ViIjoiZzdoSXlMT2poeFVtbDNPSWdkRmhQZGhTYXBjMiIsImlhdCI6MTc2MDI2NzMzMywiZXhwIjoxNzYwMjcwOTMzLCJlbWFpbCI6InN1amFsZ2F3YXMxOEBnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsic3VqYWxnYXdhczE4QGdtYWlsLmNvbSJdfSwic2lnbl9pbl9wcm92aWRlciI6InBhc3N3b3JkIn19.mLZjCidDFTLVg2yEjUlR4n8jgegEOKUglqwjtumQ27GOwezc_nxL_9lT_oU_eBe-PxPKF2gDv98-PT6CMe99rFmFws-4GNsMAVVfEQusdXaoulwEbBjbgqnajjvRPjvgt3_J1dqmnHB_MSW2fV-A4H5bgdbrajz5rR4eGsM9RCI-VeVMxMDfM_FiySbd7PXCFVl6DL95ucW8wF84QZgzIwXZJTQVA-jy13Oe3V-6vWuWbZujFSJ3s5b0qzuiZ6PuRBVoNuz7_o_Ihh-gwS6kQGJmolUJ1j6yBBRo-O0qZtDrF9hztu0y09XKd9ZtO40LJBMZlVZdru7Uo6iMuTfIuA"

with app.app_context():
    print("Resolving patient token...")
    uid = token_to_uid(PATIENT_TOKEN)
    print(f"UID is: {uid}")
